services:
  oboete.api:
    build:
      context: ./Oboete.API/
      dockerfile: Dockerfile-debug
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - oboete-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: oboete 
      POSTGRES_USER: oboete 
      POSTGRES_PASSWORD: qpweiorlk1201f
    restart: unless-stopped
      
      
volumes:
  oboete-postgres-data:
