FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY "Oboete.API/Oboete.API.csproj" "Oboete.API/"
COPY "Oboete.API.Controllers/Oboete.API.Controllers.csproj" "/Oboete.API.Controllers/"
COPY "Oboete.API.Entities/Oboete.API.Entities.csproj" "/Oboete.API.Entities/"
COPY "Oboete.API.Services/Oboete.API.Services.csproj" "/Oboete.API.Services/"
WORKDIR "/src/Oboete.API"
RUN dotnet restore "Oboete.API.csproj"
WORKDIR /src
COPY . .
WORKDIR "/src/Oboete.API"
RUN dotnet build "Oboete.API.csproj" -c Debug -o /app/build


FROM base AS final
WORKDIR /app
COPY --from=build /app/build .
COPY Oboete.API/appsettings.Development.json appsettings.json
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://*:80
EXPOSE 80
ENTRYPOINT ["dotnet", "Oboete.API.dll"]
