FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
WORKDIR "/src/Oboete.API"
COPY "Oboete.API.csproj" .
RUN dotnet restore "Oboete.API.csproj"
COPY . .
RUN dotnet build "Oboete.API.csproj" -c Debug -o /app/build


FROM base AS final
WORKDIR /app
COPY --from=build /app/build .
COPY .env/appsettings.json .
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://*:80
EXPOSE 80
ENTRYPOINT ["dotnet", "Oboete.API.dll"]
